[GH-11] Add autocomplete prompts to the command
mattermost/mattermost-plugin-google-calendar pull request #23
Opened 2020-10-05 20:58 UTC by GodlikePenguin

This commit adds autocomplete prompts for the available sub commands and arguments when using the calendar slash command

#### Summary
This change adds auto complete prompts when using the `/calendar` Plugin

#### Ticket Link
Fixes https://github.com/mattermost/mattermost-plugin-google-calendar/issues/11

2020-10-05 20:58 UTC, mattermod commented
Hello @GodlikePenguin,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2020-10-05 22:42 UTC, aaronrothschild approved these changes
Looks good to me, thanks for your contribution @GodlikePenguin !

2020-10-05 22:42 UTC, aaronrothschild commented on server/command_hooks.go
> +	create := model.NewAutocompleteData("create", "[title_of_event] [start_datetime] [end_datetime]", "Create a event with a title and start date-time and end date-time")
Nit
```suggestion
	create := model.NewAutocompleteData("create", "[title_of_event] [start_datetime] [end_datetime]", "Create an event with a title, start date-time and end date-time")
```

2020-10-06 12:55 UTC, hahmadia approved these changes
Other than the above suggestion made by Aaron, I think code wise it looks good. Thank you

2020-10-06 16:34 UTC, hanzei requested changes
Awesome :rocket: 

One questions below

2020-10-06 16:34 UTC, hanzei commented on server/command_hooks.go
> +	list.AddTextArgument("Number of events to list", "[number_of_events]", "^[0-9]+$")
This argument isn't required. I think `AddNamedTextArgument` should be used instead.

2020-10-06 16:34 UTC, hanzei commented on server/command_hooks.go
> +	summary.AddTextArgument("The date to view in YYYY-MM-DD format", "[date]", "")
Same here

2020-10-06 16:38 UTC, GodlikePenguin commented on server/command_hooks.go
> +	list.AddTextArgument("Number of events to list", "[number_of_events]", "^[0-9]+$")
I did look into `NamedTextArgument` but the autocomplete seems to want to apply them using the `--name` format, I wasn't sure if that would break the parsing of the command

2020-10-07 09:03 UTC, hanzei commented on server/command_hooks.go
> +	list.AddTextArgument("Number of events to list", "[number_of_events]", "^[0-9]+$")
You can leave the first field `name` as empty. Then it's work similar to `AddTextArgument`.

2020-10-07 09:14 UTC, GodlikePenguin commented on server/command_hooks.go
> +	list.AddTextArgument("Number of events to list", "[number_of_events]", "^[0-9]+$")
Ah cool. I'll make that change

2020-10-07 18:58 UTC, GodlikePenguin commented on server/command_hooks.go
> +	list.AddTextArgument("Number of events to list", "[number_of_events]", "^[0-9]+$")
So I tried to make the suggested change and the plugin would be loaded in the plugin menu, but all the prompts (including just for `/calendar`) disappeared. I checked the logs and there wasn't anything obvious to show why it was failing, but I took a look at the code for the autocomplete and it looks like the validation step doesn't allow a non named optional argument: https://github.com/mattermost/mattermost-server/blob/master/model/command_autocomplete.go#L279. It doesn't seem like I can make this change with the current implementation of Auto complete.

2020-10-08 19:36 UTC, hanzei approved these changes
Great work :rocket:

2020-10-08 19:36 UTC, hanzei commented on server/command_hooks.go
> +	list.AddTextArgument("Number of events to list", "[number_of_events]", "^[0-9]+$")
Good point, I completely forgot about that. :+1:

2020-10-08 19:38 UTC, hanzei commented
I did test the PR locally. No concerns from my side. Let's merge this!

2020-10-08 19:38 UTC, merged