golang-cli-lint error fixed during automake operation: server/plugin.…
mattermost/mattermost-plugin-google-calendar pull request #35
Opened 2022-03-22 07:18 UTC by DmitriyKalekin

…go:15:13: fieldalignment: struct with 72 pointer bytes could be 48 (govet)

This error arises in  golangci-lint during run `make`.

The reason of this bug - bad maligned struct.
I used this article [https://medium.com/@sebassegros/golang-dealing-with-maligned-structs-9b77bacf4b97]
to make compact alignment in `type Plugin struct`

After this change my plugin was built correctly.

2022-03-22 07:18 UTC, mattermod commented
Hello @DmitriyKalekin,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2022-03-22 07:21 UTC, DmitriyKalekin commented
/check-cla

2022-03-22 08:34 UTC, DmitriyKalekin commented
/check-cla

2022-03-28 10:52 UTC, hanzei requested changes
I would advice disabling `fieldalignment` instead as it provide little value as in https://github.com/mattermost/mattermost-plugin-starter-template/blob/18b436aa4c5f329e96df5cc78b5f00f3fd2d89d2/.golangci.yml#L13-L16

2022-04-09 01:01 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2022-06-21 14:57 UTC, danielzzz commented
hello! is there any chance this would be merged soon? thanks a lot!

2022-09-18 11:24 UTC, hanzei commented
https://github.com/mattermost/mattermost-plugin-google-calendar/pull/35#pullrequestreview-922960607 is blocking the merge

2022-10-07 18:45 UTC, hanzei commented
Closing in favor of https://github.com/mattermost/mattermost-plugin-google-calendar/pull/40

2022-10-07 18:45 UTC, closed without merging