refactor: remove direct msgraph dependency, updated dependencies
mattermost/mattermost-plugin-google-calendar pull request #77
Opened 2024-05-10 12:44 UTC by fmartingr

#### Summary
- Updates mscalendar to v1.3.0
- Removes dead code
- Refactored package file names and code
- Removed `msgraph` as a direct dependency (as a result of the above)
- Upgraded rest of dependencies

2024-05-10 16:25 UTC, mickmister approved these changes

2024-05-10 16:25 UTC, mickmister commented on gcal/gcal.go
> +	req, err := http.NewRequest(method, callURL, inBody)
Maybe this file can be called something like `http_request.go`? Some name to show that the main purpose is sending outgoing requests through the `net/http` library

2024-05-13 14:35 UTC, fmartingr commented on gcal/gcal.go
> +	req, err := http.NewRequest(method, callURL, inBody)
👍  https://github.com/mattermost/mattermost-plugin-google-calendar/pull/77/commits/8ceae32aeebafcd0e4a1e9e889d935343c0eb47a

2024-05-14 14:44 UTC, mickmister approved these changes

2024-07-04 07:46 UTC, hanzei requested changes
NIce cleanup :+1: , one suggestion below

2024-07-04 07:46 UTC, hanzei commented on gcal/http_request.go
2/5 this methods could just be part of `gcal/client.go`.

2024-07-04 07:46 UTC, hanzei approved these changes

2024-07-04 11:25 UTC, fmartingr commented on gcal/http_request.go
That's actually better, yeah. Was not convinced about that http file.

2024-07-04 11:29 UTC, merged